version: '3.8'

services:
      
  strongswan:
    image: wegerle/strongswan:alpine
    container_name: strongswan
    restart: always
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./config/strongswan.conf:/etc/strongswan.conf
      - ./config/ipsec.conf:/etc/ipsec.conf 
      - ./config/ipsec.secrets:/etc/ipsec.secrets
      - ./config/ipsec.d:/etc/ipsec.d
    env_file:
      - ./strongswan.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      backend:
          ipv4_address: ${IPV4_NETWORK:-172.19.4}.2
          ipv6_address: ${IPV6_NETWORK:-fdbe:df57:1f47:4::}2
          aliases:
            - strongswan
      
networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-strongswan
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.19.4}.0/24
        - subnet: ${IPV6_NETWORK:-fdbe:df57:1f47:4::}/64